[book]
authors = ["Jan-Erik Rediger", "Florian Gilcher"]
multilingual = false
src = "src"
title = "Workbook for Rust & Qt workshop"

[output.html]
git-repository-url = "https://github.com/ferrous-systems/qt-training-2023"

[output.html.playground]
runnable = false
